name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Dependencies
      run: |
        composer install

    - name: Compile Code
      run: |
        php -f application/compile.php

    - name: Run Program
      run: |
        php -f application/run.php
